version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: deadline_task_board_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d deadline_task_board"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Backend API
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: deadline_task_board_api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      HOST: ${HOST}
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
    command: >
      sh -c "
        while ! pg_isready -U dbuser -h db -d deadline_task_board; do
          echo 'Waiting for database...'
          sleep 2
        done &&
        python scripts/init_db.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # Telegram Bot
  bot:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: deadline_task_board_bot
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_BASE_URL: ${API_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
    command: >
      sh -c "
        while ! pg_isready -U dbuser -h db -d deadline_task_board; do
          echo 'Waiting for database...'
          sleep 2
        done &&
        python run_bot.py
      "

  # Frontend React App
  frontend:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: deadline_task_board_frontend
    env_file:
      - .env
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      # Disable hot reload completely to avoid WebSocket errors
      FAST_REFRESH: false
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app_network
    volumes:
      - ./web-app/src:/app/src
      - ./web-app/public:/app/public
    stdin_open: true
    tty: true

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: deadline_task_board_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge 